name: CI

on: [push, pull_request]

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:

      - name: get repo
        uses: actions/checkout@v3

      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: install dependencies
        run: |
          pip install flake8 black isort docformatter doc8

      - name: lint with flake8
        run: |
          flake8
          flake8 --doctests --extend-ignore=E203,E701,F821

      - name: lint with black
        run: |
          black --check .

      - name: lint with isort
        run: |
          isort --check .

      - name: lint with docformatter
        run: |
          docformatter --check .

      - name: lint with doc8
        run: |
          doc8 .

  type-check:

    needs: lint

    runs-on: ubuntu-latest

    steps:

      - name: get repo
        uses: actions/checkout@v3

      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: install package
        run: |
          pip install . mypy

      - name: run mypy check
        run: mypy

  doc:

    needs: type-check

    runs-on: ubuntu-latest

    steps:

      - name: get repo
        uses: actions/checkout@v3

      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: install package
        run: |
          pip install .[doc]

      - name: build document
        run: |
          cd doc
          make html SPHINXOPTS="-W --keep-going"
